steps:
  - name: bash
    args:
      [
        "-c",
        "@rcco:registry=https://npm.pkg.github.com$'\n'echo //npm.pkg.github.com/:_authToken=$$NPM_TOKEN > .npmrc",
      ]
    secretEnv: ["NPM_TOKEN"]
  - name: "node:14"
    entrypoint: "npm"
    args: ["install"]
  # Build the application
  - name: "node:14"
    entrypoint: "npm"
    args: ["run", "build"]
  # Export the application to a static site
  - name: "node:14"
    entrypoint: "npm"
    args: ["run", "generate"]
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy", "--version=staging", "--no-promote"]
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/NPM_TOKEN/versions/latest
      env: "NPM_TOKEN"
timeout: "1600s"
