- name: node:16
  entrypoint: npm
  args: ['run', 'install']
- name: node:16
  entrypoint: npm
  args: ['run', 'build']
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
timeout: "1600s"
