steps:
  - name: "node:14"
    entrypoint: "npm"
    args: ["install"]
  # Build the application
  - name: "node:14"
    entrypoint: "npm"
    args: ["run", "build"]
  # Export the application to a static site
  - name: "node:14"
    entrypoint: "npm"
    args: ["run", "generate"]
    - name: node:10.15.1
    entrypoint: npm
    args: ["run", "create-env"]
    env:
    - 'MY_SECRET_KEY=${_MY_SECRET_KEY}'
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy", "--version=staging", "--no-promote"]
timeout: "1600s"
