steps:
  - name: "node:14"
    entrypoint: "npm"
    args: ["install"]
  - name: "bash"
    script: "echo MY_SECRET_KEY=static-key > .env"
  # Build the application
  - name: "node:14"
    entrypoint: "npm"
    args: ["run", "build"]
  # Export the application to a static site
  - name: "node:14"
    entrypoint: "npm"
    args: ["run", "generate"]
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy", "--version=staging", "--no-promote"]
timeout: "1600s"
