steps:
  - name: node:14.17.2
    entrypoint: npm
    args: ["install"]
  - name: node:14.17.2
    entrypoint: npm
    args: ["build"]
    env:
      - "MY_SECRET_KEY=${_MY_SECRET_KEY}"
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
timeout: "1600s"
