steps:
  - name: "node:14"
    entrypoint: "npm"
    args: ["install"]
  # Build the application
  - name: "node:14"
    entrypoint: "npm"
    args: ["run", "build"]
  # Export the application to a static site
  - name: "node:14"
    entrypoint: "npm"
    args: ["run", "generate"]
  - name: "bash"
    script: "echo MY_SECRET_KEY=${_MY_SECRET_KEY} > .env"
    env:
      - "MY_SECRET_KEY=${_MY_SECRET_KEY}"
      - "NPM_TOKEN=${_NPM_TOKEN}"
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy", "--version=staging", "--no-promote"]
timeout: "1600s"
